apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sentinel-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ayuspoudel/sentinel-sre
    targetRevision: develop
    path: playground/argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
