{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
{{- with $.Values.serviceMonitor }}
{{- range $appName, $app := $.Values.apps }}
{{- if $app.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $app.name }}
  namespace: {{ .namespace | default $.Release.Namespace }}
  labels:
    release: prometheus
    app: {{ $app.name }}
    appGroup: {{ $.Values.global.appGroup }}
    tier: {{ $app.labels.tier }}
    cluster: {{ $.Values.clusterName }}
spec:
  selector:
    matchLabels:
      app: {{ $app.name }}
  endpoints:
    - port: http
      path: {{ .path | default "/metrics" }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
