{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
{{- range $appName, $app := .Values.apps }}
{{- if $app.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $app.name }}
  namespace: {{ $.Values.serviceMonitor.namespace }}
  labels:
    release: prometheus
    app: {{ $app.name }}
    appGroup: {{ $.Values.global.appGroup }}
    tier: {{ $app.labels.tier }}
    cluster: {{ $.Values.clusterName }}
spec:
  selector:
    matchLabels:
      app: {{ $app.name }}
      appGroup: {{ $.Values.global.appGroup }}
      tier: {{ $app.labels.tier }}
      cluster: {{ $.Values.clusterName }}
  endpoints:
    - port: http
      path: {{ $.Values.serviceMonitor.path }}
---
{{- end }}
{{- end }}
{{- end }}
