{{- range $appName, $app := .Values.apps }}
{{- if $app.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $app.name }}
  labels:
    app: {{ $app.name }}
    appGroup: {{ $.Values.global.appGroup }}
    tier: {{ $app.labels.tier }}
    cluster: {{ $.Values.clusterName }}
spec:
  selector:
    app: {{ $app.name }}
    appGroup: {{ $.Values.global.appGroup }}
    tier: {{ $app.labels.tier }}
    cluster: {{ $.Values.clusterName }}
  ports:
    - name: http
      port: {{ $.Values.service.port }}
      targetPort: {{ $.Values.service.port }}
---
{{- end }}
{{- end }}
