{{- range .Values.apps }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  selector:
    app: {{ .name }}
  ports:
    - name: http
      port: {{ $.Values.service.port }}
      targetPort: 8080
---
{{- end }}
