apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./applications/sentinel-workload-payments.yaml
  - ./applications/sentinel-workload-streaming.yaml
  - ./prometheus/prometheus.yaml
