{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "sentinel-agent.namespace" . }}
  labels:
    app.kubernetes.io/name: sentinel
    app.kubernetes.io/component: agent
{{- end }}
