apiVersion: v1
kind: Service
metadata:
  name: sentinel-agent
  namespace: {{ include "sentinel-agent.namespace" . }}
  labels:
{{ include "sentinel-agent.labels" . | indent 4 }}
spec:
  selector:
    app: sentinel-agent
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
