clusterName: sreCluster

global:
  appGroup: payments
serviceMonitor:
  enabled: true
  namespace: monitoring
  labels:
    release: prometheus
  path: /metrics

apps:
  stable:
    enabled: true
    name: stable
    image:
      repository: ayuspoudel/workload-stable
      tag: "1.0.2"
    replicas: 3
    env:
      ERROR_RATE: "0.0"
    labels:
      tier: stable

  flaky:
    enabled: true
    name: flaky
    image:
      repository: ayuspoudel/workload-flaky
      tag: "1.0.1"
    replicas: 2
    env:
      ERROR_RATE: "0.005"
      SPIKE_PROBABILITY: "0.02"
      SPIKE_DURATION_SEC: "5"
      SPIKE_ERROR_RATE: "0.20"
      MAX_LATENCY_MS: "150"
    labels:
      tier: flaky

  canary:
    enabled: true
    name: canary
    image:
      repository: ayuspoudel/workload-canary
      tag: "1.0.3"
    replicas: 1
    env:
      ERROR_RATE: "0.02"
      LATENCY_MS: "250"
    labels:
      tier: canary

service:
  port: 8080
