namespace:
  name: sentinel
  create: true
image:
  repository: ayuspoudel/sentinel-agent
  tag: 1.0.8
  pullPolicy: IfNotPresent
replicaCount: 1
sentinelSRE:
  url: http://host.minikube.internal:8000
tls:
  secretName: sentinel-agent-tls
webhook:
  failurePolicy: Fail
  timeoutSeconds: 5
selectors:
  namespaceLabel:
    key: sentinel.guard/enabled
    value: "true"
  workloadLabel:
    key: sentinel.guard/name
